### PR TITLE
Clean up spaces in code and also change page1 to translations

### PR DESCRIPTION
**Pull request by MAX0342**
also change the links for crowdin in translations

### CODE REVIEW

**Comment by jelle619** [comment]
translate.html has been changed back to page1.html, so the sitemap is correct.
As for the spaces, I need them to work with some software I have. Of course it would be better for the site's loading time to remove them, but it would make it harder to edit in the future.

As for the links to Crowdin, the reason I have linked it to our profiles is because TitanEmbeds.com also does it that way. Also, when clicking on most stuff on the page you linked to, it requires you to login.

Anyways, thanks for your effort, but it might be better to discuss this with me on Discord first.

**Comment by MAX0342** [comment]
ok
atom fixed the spaces so i didn't want that to happen

**Comment by MAX0342** [comment]
and the links don't need login i checked

**Comment by MAX0342** [comment]
why page1 tho instead of translations

**Pull request closed without merging**
